#server:
#  port: 8080

#spring:
#  application:
#    name: ad
#  profiles:
#    active: dev

#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: health, info



mybatis:
  #domain对象的包
  type-aliases-package: xmu.oomall.ad.domain
  #xmu.oomall.footprint.mapper。xml所在的位置
  mapper-locations: classpath:xmu.oomall.ad.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true



#刘仁帅组
#eureka:
#  client: # 客户端进行Eureka注册的配置
#    service-url:
#      defaultZone: http://148.70.28.112:8761/eureka
#
#spring:
#  datasource:
#    url: jdbc:mysql://148.70.28.112:3306/wowomall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: wowoto
#    password: zqhlovekly
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: adService
#
#server:
#  port: 8769


#周林辉
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooad2-2?serverTimezone=GMT
    username: root
    #  password: Zhangyaqing123
    password: 123456
  application:
    name: adService #服务名称--调用的时候根据名称来调用该服务的方法

server:
  port: 8801

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/