
mybatis:
  #domain对象的包
  type-aliases-package: xmu.oomall.ad.domain
  #xmu.oomall.footprint.mapper。xml所在的位置
  mapper-locations: classpath:xmu.oomall.ad.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#<<<<<<< HEAD
#    url: jdbc:mysql://47.52.88.176:3306/DB2_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: user2_1
#    password: ooad1
#    hikari:
#      maximum-pool-size: 10

#=======
#    url: jdbc:mysql://localhost:3306/ooad2-2?serverTimezone=GMT
#    username: root
#    password: Zhangyaqing123
#>>>>>>> origin/master
#  application:
#    name: adService #服务名称--调用的时候根据名称来调用该服务的方法

#server:
#  port: 8801
#
#eureka:
#  client:
#    serviceUrl:
#<<<<<<< HEAD
#      defaultZone: http://139.196.253.120:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8770


#潘朝旺
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB3_8?serverTimezone=Asia/Shanghai
#    username: user3_8
#    password: ooad8
#    hikari:
#      maximum-pool-size: 10
#  application:
#    name: adService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.96.159.71:8888/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8762
#=======
#      defaultZone: http://localhost:8761/eureka/
#>>>>>>> origin/master

#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.88.176:3306/DB2_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: user2_1
    password: ooad1

  application:
    name: adService #服务名称--调用的时候根据名称来调用该服务的方法

server:
  port: 8770

eureka:
  client:
    serviceUrl:
      defaultZone: http://139.196.253.120:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.97.43.141
    non-secure-port: 8770

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB2_1?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: user3_8
#    password: ooad8
#    hikari:
#      maximum-pool-size: 10
#
#  application:
#    name: adService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8700
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.100.32.48:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8700

#PCW
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB3_8?useSSL=false&useUnicode=true&characterEncoding=UTF-8
#    username: user3_8
#    password: ooad8
#
#  application:
#    name: adService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8762
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.96.159.71:8888/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8762