

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://42.52.88.176:3306/DB2_2?serverTimezone=GMT
    username: user2_2
    password: OOAD2
  application:
    name: logService #服务名称--调用的时候根据名称来调用该服务的方法

server:
  port: 8803

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.97.43.141:8761/eureka/
      #    prefer-ip-address: true
      #    ip-address: 47.97.43.141
      #    non-secure-port: 8762


mybatis:
  #domain对象的包
  type-aliases-package: xmu.oomall.log.domain
  #xmu.oomall.footprint.mapper。xml所在的位置
  mapper-locations: classpath:xmu.oomall.log.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

