#spring:
#  application:
#    name: log
#  profiles:
#    active: dev

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://42.52.88.176:3306/DB2_2?serverTimezone=GMT
#    username: user2_2
#    password: OOAD2
#  application:
#    name: logService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8803
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.97.43.141:8761/eureka/
      #    prefer-ip-address: true
      #    ip-address: 47.97.43.141
      #    non-secure-port: 8762


mybatis:
  #domain对象的包
  type-aliases-package: xmu.oomall.log.domain
  #xmu.oomall.footprint.mapper。xml所在的位置
  mapper-locations: classpath:xmu.oomall.log.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

#logging:
#  #设置日志打印级别
#  level:
#    #Spring框架中的日志级别
#    org.springframework.web: info
#    root: error
#    #自己项目包名下的日志级别
#    xmu.oomall.controller: debug
#    xmu.oomall.service: debug
#    xmu.oomall.dao: debug
#    xmu.oomall.mapper: error
#    xmu.oomall.domain: debug
#    xmu.oomall.util: debug
#  #使用logback日志，取代默认的common日志
#  file:
#    path: C:\Users\Ming Qiu\log
#  config: classpath:logback-spring.xml
#
#oomall:
#  #最大付款时间, 单位分钟
#  maxpaytime: 30
#  #redis缓存失效时间，单位分钟
#  redisexpiretime: 1
#  #预提库存数量
#  predeductQty: 3

#
##自己组
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB2_2?serverTimezone=Asia/Shanghai
#    username: user2_2
#    password: ooad2
#  application:
#    name: logService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8803
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.97.43.141:8761/eureka/