spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooad2-2?serverTimezone=GMT
    username: root
    password: 123456
  application:
    name: goodsService #服务名称--调用的时候根据名称来调用该服务的方法

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


