spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooad2-2?serverTimezone=GMT
    username: root
 #   password: Zhangyaqing123
    password: 123456
