

mybatis:
  #domain对象的包
  type-aliases-package: xmu.oomall.discount.domain
  #xmu.oomall.footprint.mapper。xml所在的位置
  mapper-locations: classpath:xmu.oomall.discount.mapper/*.xml
  configuration:
    #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
    map-underscore-to-camel-case: true

#server:
#  port: 8080

#spring:
#  application:
#    name: ad
#  profiles:
#    active: dev

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info




#刘仁帅组
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB2_1?serverTimezone=Asia/Shanghai
#    username: user2_1
#    password: ooad1
#    hikari:
#      maximum-pool-size: 10
#
#  application:
#    name: discountService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8769
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://139.196.253.120:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8769

#周林辉
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.97.43.141:3306/ooad1?serverTimezone=GMT
#    username: root
#    password: 12345678
#  #    password: Zhangyaqing123
#  application:
#    name: discountService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8885
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


##自己组
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB2_2?serverTimezone=Asia/Shanghai
#    username: user2_2
#    password: ooad2
#  application:
#    name: discountService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8802
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.97.43.141:8761/eureka/

#孔祥威李鹏程组
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB2_2?serverTimezone=Asia/Shanghai
#    username: user2_2
#    password: ooad2
#  application:
#    name: discountService
#
#server:
#  port: 8766
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://112.124.5.149:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8766


#潘朝旺
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.52.88.176:3306/DB3_8?serverTimezone=Asia/Shanghai
    username: user3_8
    password: ooad8
    hikari:
      maximum-pool-size: 10

  application:
    name: discountService #服务名称--调用的时候根据名称来调用该服务的方法

server:
  port: 8763

eureka:
  client:
    serviceUrl:
      defaultZone: http://47.96.159.71:8888/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 47.97.43.141
    non-secure-port: 8763

#周林辉最新
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.52.88.176:3306/DB2_2?serverTimezone=Asia/Shanghai
#    username: user2_2
#    password: ooad2
#
#  application:
#    name: discountService #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8802
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.97.43.141:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8802