#自己本地
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ooad2-2?serverTimezone=GMT
    username: root
    password: Zhangyaqing123

  application:
    name: discountService

server:
  port: 8802

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8802



#潘朝旺组
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.96.159.71:3306/oomall?serverTimezone=GMT
#    username: oomall
#    password: oomallp@$$w0rd
#  application:
#    name: Discount #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8763
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://47.96.159.71:8888/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.97.43.141
#    non-secure-port: 8763


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.103.218.172:3306/oomall2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
#    username: root
#    password: 741120ab
#  application:
#    name: Discount #服务名称--调用的时候根据名称来调用该服务的方法
#
#server:
#  port: 8766
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://112.124.5.149:8761/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 47.96.159.71
#    non-secure-port: 8766